version: '3.8'
services:
  recipe-app-api:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe-app-api-db
      networks:
        - app-network
networks:
  app-network:
